<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>XerahS.Core</RootNamespace>
    <TargetFrameworks Condition="'$(OS)' == 'Windows_NT' And '$(CrossCompile)' != 'true'">net10.0;net10.0-windows10.0.26100.0</TargetFrameworks>
    <TargetFrameworks Condition="'$(OS)' != 'Windows_NT' Or '$(CrossCompile)' == 'true'">net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\XerahS.Common\XerahS.Common.csproj" />
    <ProjectReference Include="..\XerahS.Services.Abstractions\XerahS.Services.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\platform\XerahS.Platform.Abstractions\XerahS.Platform.Abstractions.csproj" />
    <ProjectReference Include="..\XerahS.History\XerahS.History.csproj" />
    <ProjectReference Include="..\XerahS.UploaderPluginSdk\XerahS.UploaderPluginSdk.csproj" />
    <ProjectReference Include="..\XerahS.Uploaders\XerahS.Uploaders.csproj" />
    <ProjectReference Include="..\XerahS.Indexer\XerahS.Indexer.csproj" />

    <ProjectReference Include="..\..\..\..\ShareX.ImageEditor\src\ShareX.ImageEditor\ShareX.ImageEditor.csproj" GlobalPropertiesToRemove="OS" />

    <ProjectReference Include="..\..\app\XerahS.RegionCapture\XerahS.RegionCapture.csproj" />
    <ProjectReference Include="..\XerahS.Media\XerahS.Media.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NETStandard.Library" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="ZXing.Net.Bindings.SkiaSharp" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources/CaptureSound.wav" />
    <EmbeddedResource Include="Resources/TaskCompletedSound.wav" />
    <EmbeddedResource Include="Resources/ActionCompletedSound.wav" />
    <EmbeddedResource Include="Resources/ErrorSound.wav" />
  </ItemGroup>
</Project>

